apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service
  labels:
    app: ecommerce-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: ecommerce-backend

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual base64 encoded secrets
  secret-key: ZGphbmdvLXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=
  db-user: cG9zdGdyZXM=
  db-password: cG9zdGdyZXM=
  africastalking-username: c2FuZGJveA==
  africastalking-api-key: eW91cl9hcGlfa2V5X2hlcmU=
  email-user: eW91cl9lbWFpbEBnbWFpbC5jb20=
  email-password: eW91cl9hcHBfcGFzc3dvcmQ=
